name: Node.js CI for Playwright Testing on Airline Flight Booking

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - name: Install Playwright browsers
      run: npx playwright install --with-deps
    - name: Install xvfb
      run: sudo apt-get update && sudo apt-get install -y xvfb
    - name: Run Playwright tests in headed mode
      run: xvfb-run --auto-servernum -- npm test